spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  application:
    name: FlagWith
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/flagwith}
    username: ${DB_USERNAME:flagwith}
    password: ${DB_PASSWORD:flagwith}
